---
# File: group_vars/all - Hubot role variables
# 
# hubot_admin: Change to the user account that will run the bot; for
# operating in development mode with Vagrant, this value should be "vagrant".
# hubot_dir: Change to the home directory for the bot
# hubot_identity: Change to a different short user name if necessary
# hubot_scripts: A list of additional scripts used by our Hubot

hubot_admin: brian
hubot_dir: "/home/{{ hubot_admin }}/hubot"
hubot_identity: couchbot
hubot_scripts:
  - announce.coffee
  - achievement_unlocked.coffee
  - ackbar.coffee
  - applause.coffee
  - ascii.coffee
  - base64.coffee
  - beerme.coffee
  - bees.coffee
  - botsnack.coffee
  - cat.coffee
  - chm.coffee
  - clark.coffee
  - cleverbot.coffee
  - coin.coffee
  - cowsay.coffee
  - decide.coffee
  - defprogramming.coffee
  - devexcuse.coffee
  - eight-ball.coffee
  - factoid.coffee
  - f-ing-weather.coffee
  - fortune.coffee
  - grumpycat.coffee
  - hackernews.coffee
  - im.coffee
  - inigo-montoya.coffee
  - megusta.coffee
  - penny-arcade.coffee
  - plus_one.coffee
  - ping.coffee
  - put-it-back.coffee
  - redis-brain
  - remind.coffee
  - scotch.coffee
  - shipit.coffee
  - stallman.coffee
  - sudo.coffee
  - tell.coffee
  - thought.coffee
  - tryerlang.coffee
  - wordnik.coffee
  - wunderground.coffee
  - xkcd.coffee
  - zendesk.coffee

