---
# File: group_vars/all - Hubot role variables
# 
# hubot_scripts: A list of additional scripts used by our Hubot

hubot_scripts:
  - announce.coffee
  - achievement_unlocked.coffee
  - ackbar.coffee
  - applause.coffee
  - ascii.coffee
  - base64.coffee
  - beerme.coffee
  - bees.coffee
  - botsnack.coffee
  - cat.coffee
  - chm.coffee
  - clark.coffee
  - cleverbot.coffee
  - coin.coffee
  - cowsay.coffee
  - decide.coffee
  - devexcuse.coffee
  - eight-ball.coffee
  - f-ing-weather.coffee
  - fortune.coffee
  - grumpycat.coffee
  - hackernews.coffee
  - inigo-montoya.coffee
  - megusta.coffee
  - penny-arcade.coffee
  - ping.coffee
  - put-it-back.coffee
  - redis-brain
  - scotch.coffee
  - stallman.coffee
  - sudo.coffee
  - tryerlang.coffee
  - wordnik.coffee
  - wunderground.coffee
  - xkcd.coffee
  - zendesk.coffee
