---
# File: roles/hubot/handlers/main.yml - Hubot role handlers

- name: restart hubot
  sudo: True
  service: name=hubot state=restarted

- name: stop hubot
  sudo: True
  service: name=hubot state=stopped
